@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraftforge.items.newinv;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;