@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraftforge.items.newinv.transactions;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;